[tool.poetry]
name = "python-payments-sdk"
version = "0.1.0"
description = ""
authors = ["jerry.liu <jerry.liu@uancare.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
